In [ ]:
import pandas as pd
import numpy as np

In [ ]:

df = pd.read_csv("/Users/jettmu/Documents/VSCode/GTFS Parser/prediction-model/data.csv", parse_dates=["timestamp"])
df.info()
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 656596 entries, 0 to 656595
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   trip_id        656596 non-null  int64
 1   delay          656596 non-null  int64
 2   timestamp      656596 non-null  datetime64[us, UTC]
 3   temperature    656596 non-null  float64
 4   precipitation  656596 non-null  float64
 5   rain           656596 non-null  float64
 6   showers        656596 non-null  float64
 7   snowfall       656596 non-null  float64
dtypes: datetime64[us, UTC](1), float64(5), int64(2)
memory usage: 40.1 MB

,trip_id,delay,timestamp,temperature,precipitation,rain,showers,snowfall
0,1993194,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
1,1992950,17,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
2,1997004,-112,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
3,1997369,266,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
4,1985162,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0

In [7]:
df.describe()

,trip_id,delay,temperature,precipitation,rain,showers,snowfall
count,6.565960e+05,656596.000000,656596.000000,656596.000000,656596.000000,656596.0,656596.0
mean,1.991186e+06,-13.715907,23.457523,0.021023,0.021023,0.0,0.0
std,3.151110e+04,279.123825,3.822939,0.236341,0.236341,0.0,0.0
min,9.022280e+05,-10019.000000,13.700000,0.000000,0.000000,0.0,0.0
25%,1.987057e+06,-37.000000,20.500000,0.000000,0.000000,0.0,0.0
50%,1.993021e+06,0.000000,23.600000,0.000000,0.000000,0.0,0.0
75%,1.996507e+06,63.000000,26.500000,0.000000,0.000000,0.0,0.0
max,1.999802e+06,5688.000000,30.800000,9.900000,9.900000,0.0,0.0

In [12]:
df[df["delay"] < -600].describe()

,trip_id,delay,temperature,precipitation,rain,showers,snowfall
count,2.642900e+04,26429.000000,26429.000000,26429.000000,26429.000000,26429.0,26429.0
mean,1.991402e+06,-958.289909,23.114503,0.020795,0.020795,0.0,0.0
std,1.680353e+04,344.653136,3.885310,0.236904,0.236904,0.0,0.0
min,9.144140e+05,-10019.000000,13.700000,0.000000,0.000000,0.0,0.0
25%,1.988737e+06,-1106.000000,20.100000,0.000000,0.000000,0.0,0.0
50%,1.992692e+06,-872.000000,23.100000,0.000000,0.000000,0.0,0.0
75%,1.996161e+06,-716.000000,26.000000,0.000000,0.000000,0.0,0.0
max,1.999799e+06,-601.000000,30.800000,9.900000,9.900000,0.0,0.0

In [17]:
df[df["rain"] > 0][["temperature", "trip_id"]]

        temperature  trip_id
100268         22.9  1986792
100269         22.9  1986975
100270         22.9  1994176
100271         22.9  1999246
100272         22.9  1999337
...             ...      ...
656591         18.6  1986622
656592         18.6  1994006
656593         18.6  1999556
656594         18.6  1999709
656595         18.6  1998980

[16795 rows x 2 columns]

In [20]:
df.shape
df

,trip_id,delay,timestamp,temperature,precipitation,rain,showers,snowfall
0,1993194,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
1,1992950,17,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
2,1997004,-112,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
3,1997369,266,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
4,1985162,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
656591,1986622,62,2026-08-03 00:19:51+00:00,18.6,0.1,0.1,0.0,0.0
656592,1994006,-205,2026-08-03 00:19:51+00:00,18.6,0.1,0.1,0.0,0.0
656593,1999556,-422,2026-08-03 00:19:51+00:00,18.6,0.1,0.1,0.0,0.0
656594,1999709,-48,2026-08-03 00:19:51+00:00,18.6,0.1,0.1,0.0,0.0
656595,1998980,0,2026-08-03 00:19:51+00:00,18.6,0.1,0.1,0.0,0.0

In [30]:
df.iloc[4:6,:]
# df.loc[4:10,["rain", "snowfall"]]

,trip_id,delay,timestamp,temperature,precipitation,rain,showers,snowfall
4,1985162,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0
5,1989217,0,2026-07-24 22:04:55+00:00,24.6,0.0,0.0,0.0,0.0

In [42]:
# df[(df["rain"] > 0) | (df["temperature"] > 25)]

df.sort_values(["temperature", "rain"])
# df["ron"] = df["rain"] + df["snowfall"]
# df

,trip_id,delay,timestamp,temperature,precipitation,rain,showers,snowfall,ron
23056,1986206,-7,2026-07-25 10:14:54+00:00,13.7,0.0,0.0,0.0,0.0,0.0
23057,1997948,-77,2026-07-25 10:14:54+00:00,13.7,0.0,0.0,0.0,0.0,0.0
23058,1998084,-622,2026-07-25 10:14:54+00:00,13.7,0.0,0.0,0.0,0.0,0.0
23059,1998303,0,2026-07-25 10:14:54+00:00,13.7,0.0,0.0,0.0,0.0,0.0
23060,1990207,-52,2026-07-25 10:14:54+00:00,13.7,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
533955,1995744,0,2026-07-31 19:14:52+00:00,30.8,0.0,0.0,0.0,0.0,0.0
533956,1996164,526,2026-07-31 19:14:52+00:00,30.8,0.0,0.0,0.0,0.0,0.0
533957,1989262,-63,2026-07-31 19:14:52+00:00,30.8,0.0,0.0,0.0,0.0,0.0
533958,1995372,0,2026-07-31 19:14:52+00:00,30.8,0.0,0.0,0.0,0.0,0.0
533959,1996346,-23,2026-07-31 19:14:52+00:00,30.8,0.0,0.0,0.0,0.0,0.0

In [48]:
df["local_time"] = df["timestamp"].dt.tz_convert("America/Toronto")

In [ ]:
# np.sin()
df["local_time"].dt.day_of_week

0         4
1         4
2         4
3         4
4         4
         ..
656591    6
656592    6
656593    6
656594    6
656595    6
Name: local_time, Length: 656596, dtype: int32

In [61]:
df2 = df.set_index("timestamp")
df2

,trip_id,delay,temperature,precipitation,rain,showers,snowfall,ron,local_time
timestamp,,,,,,,,,
2026-07-24 22:04:55+00:00,1993194,0,24.6,0.0,0.0,0.0,0.0,0.0,2026-07-24 18:04:55-04:00
2026-07-24 22:04:55+00:00,1992950,17,24.6,0.0,0.0,0.0,0.0,0.0,2026-07-24 18:04:55-04:00
2026-07-24 22:04:55+00:00,1997004,-112,24.6,0.0,0.0,0.0,0.0,0.0,2026-07-24 18:04:55-04:00
2026-07-24 22:04:55+00:00,1997369,266,24.6,0.0,0.0,0.0,0.0,0.0,2026-07-24 18:04:55-04:00
2026-07-24 22:04:55+00:00,1985162,0,24.6,0.0,0.0,0.0,0.0,0.0,2026-07-24 18:04:55-04:00
...,...,...,...,...,...,...,...,...,...
2026-08-03 00:19:51+00:00,1986622,62,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:19:51-04:00
2026-08-03 00:19:51+00:00,1994006,-205,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:19:51-04:00
2026-08-03 00:19:51+00:00,1999556,-422,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:19:51-04:00
2026-08-03 00:19:51+00:00,1999709,-48,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:19:51-04:00
2026-08-03 00:19:51+00:00,1998980,0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:19:51-04:00

In [76]:

df3 = df2[df2["trip_id"] == 1999556].resample("1min").ffill()

df3[~df3["trip_id"].isna()]

# df3.info()

,trip_id,delay,temperature,precipitation,rain,showers,snowfall,ron,local_time
timestamp,,,,,,,,,
2026-07-26 23:25:00+00:00,1999556.0,0.0,24.2,0.0,0.0,0.0,0.0,0.0,2026-07-26 19:24:55-04:00
2026-07-26 23:26:00+00:00,1999556.0,0.0,24.2,0.0,0.0,0.0,0.0,0.0,2026-07-26 19:24:55-04:00
2026-07-26 23:27:00+00:00,1999556.0,0.0,24.2,0.0,0.0,0.0,0.0,0.0,2026-07-26 19:24:55-04:00
2026-07-26 23:28:00+00:00,1999556.0,0.0,24.2,0.0,0.0,0.0,0.0,0.0,2026-07-26 19:24:55-04:00
2026-07-26 23:29:00+00:00,1999556.0,0.0,24.2,0.0,0.0,0.0,0.0,0.0,2026-07-26 19:24:55-04:00
...,...,...,...,...,...,...,...,...,...
2026-08-03 00:15:00+00:00,1999556.0,-4.0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:14:51-04:00
2026-08-03 00:16:00+00:00,1999556.0,-4.0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:14:51-04:00
2026-08-03 00:17:00+00:00,1999556.0,-4.0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:14:51-04:00
2026-08-03 00:18:00+00:00,1999556.0,-4.0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:14:51-04:00
2026-08-03 00:19:00+00:00,1999556.0,-4.0,18.6,0.1,0.1,0.0,0.0,0.1,2026-08-02 20:14:51-04:00

In [80]:
newdf = df.groupby("trip_id").mean()

newdf[newdf["delay"] > 2000]

df[df["trip_id"] == 1999784]

,trip_id,delay,timestamp,temperature,precipitation,rain,showers,snowfall,ron,local_time
87480,1999784,0,2026-07-26 19:24:55+00:00,27.0,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:24:55-04:00
87676,1999784,0,2026-07-26 19:29:55+00:00,27.0,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:29:55-04:00
87878,1999784,20,2026-07-26 19:34:55+00:00,27.0,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:34:55-04:00
88078,1999784,94,2026-07-26 19:39:54+00:00,27.0,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:39:54-04:00
88288,1999784,167,2026-07-26 19:44:54+00:00,27.3,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:44:54-04:00
88493,1999784,87,2026-07-26 19:49:55+00:00,27.3,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:49:55-04:00
88705,1999784,80,2026-07-26 19:54:55+00:00,27.3,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:54:55-04:00
88911,1999784,0,2026-07-26 19:59:54+00:00,27.5,0.0,0.0,0.0,0.0,0.0,2026-07-26 15:59:54-04:00
89114,1999784,0,2026-07-26 20:04:54+00:00,27.5,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:04:54-04:00
89315,1999784,0,2026-07-26 20:09:54+00:00,27.5,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:09:54-04:00
89521,1999784,0,2026-07-26 20:14:54+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:14:54-04:00
89726,1999784,-114,2026-07-26 20:19:55+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:19:55-04:00
89932,1999784,141,2026-07-26 20:24:54+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:24:54-04:00
90144,1999784,273,2026-07-26 20:29:54+00:00,27.4,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:29:54-04:00
90352,1999784,358,2026-07-26 20:34:54+00:00,27.4,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:34:54-04:00
90557,1999784,563,2026-07-26 20:39:55+00:00,27.4,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:39:55-04:00
90762,1999784,457,2026-07-26 20:44:54+00:00,27.7,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:44:54-04:00
90966,1999784,217,2026-07-26 20:49:54+00:00,27.7,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:49:54-04:00
91172,1999784,230,2026-07-26 20:54:54+00:00,27.7,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:54:54-04:00
91383,1999784,507,2026-07-26 20:59:54+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 16:59:54-04:00
91592,1999784,441,2026-07-26 21:04:54+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 17:04:54-04:00
91804,1999784,453,2026-07-26 21:09:54+00:00,27.6,0.0,0.0,0.0,0.0,0.0,2026-07-26 17:09:54-04:00
646896,1999784,5617,2026-08-02 20:19:51+00:00,19.7,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:19:51-04:00
647105,1999784,5688,2026-08-02 20:24:51+00:00,19.7,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:24:51-04:00
647312,1999784,5688,2026-08-02 20:29:51+00:00,19.8,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:29:51-04:00
647519,1999784,5688,2026-08-02 20:34:51+00:00,19.8,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:34:51-04:00
647722,1999784,5688,2026-08-02 20:39:51+00:00,19.8,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:39:51-04:00
647928,1999784,5688,2026-08-02 20:44:51+00:00,19.7,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:44:51-04:00
648132,1999784,5688,2026-08-02 20:49:51+00:00,19.7,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:49:51-04:00
648342,1999784,5688,2026-08-02 20:54:51+00:00,19.7,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:54:51-04:00
648546,1999784,5688,2026-08-02 20:59:51+00:00,19.5,0.0,0.0,0.0,0.0,0.0,2026-08-02 16:59:51-04:00
648755,1999784,5688,2026-08-02 21:04:51+00:00,19.5,0.0,0.0,0.0,0.0,0.0,2026-08-02 17:04:51-04:00
648965,1999784,5688,2026-08-02 21:09:51+00:00,19.5,0.0,0.0,0.0,0.0,0.0,2026-08-02 17:09:51-04:00

In [82]:
newdf = df.groupby("trip_id").agg(del_avg=("delay", "mean"))
newdf

            del_avg
trip_id
902228   -10.500000
902842    73.250000
904827   272.800000
905723   810.000000
906473   -91.000000
...             ...
1999798  102.047619
1999799  -92.571429
1999800  -41.190476
1999801  169.857143
1999802  184.217391

[9174 rows x 1 columns]

In [ ]:
# df4 = df[df["trip_id"] == 1994106]
# df4["delay"] - df4.shift(1)["delay"]
df.reset_index()
df5 = df["delay"]
df5.rolling(4).mean()

0            NaN
1            NaN
2            NaN
3          42.75
4          42.75
           ...
656591    -51.00
656592    -67.50
656593   -141.25
656594   -153.25
656595   -168.75
Name: delay, Length: 656596, dtype: float64

In [99]:
pd.merge(left = df, right=df2, left_on=['timestamp'], right_on=['timestamp'])
pd.merge_asof(left = df, right=df2, left_on=['timestamp'], right_on=['timestamp'], tolerance = 5)

KeyboardInterrupt: